version: "3.3"

services:
  minio-s3:
    hostname: minio-s3
    container_name: minio-s3
    image: bitnami/minio:2023
    ports: 
      - "9002:9000"
      - "9003:9001"
    environment: 
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=eO3RNPcKgWInlzPJuI08
      - TZ=America/Sao_Paulo
    deploy:
      resources:
        limits:
          memory: 2G
    restart: always
    volumes: 
      - minio_data:/bitnami/minio/data
      - minio_certs:/certs
    networks:
      - network-data-lake
    
volumes:
  minio_data:
  minio_certs:

networks:
  network-data-lake:
    driver: bridge