FROM renatoelho/servidor-jupyter:0.0.2

SHELL ["/bin/bash", "-c"]

ENV JAVA_HOME="/home/jdk-11.0.2"
ENV PATH="${JAVA_HOME}/bin/:${PATH}"

WORKDIR /home

ADD https://download.java.net/java/GA/jdk11/9/GPL/openjdk-11.0.2_linux-x64_bin.tar.gz .

RUN tar xzf openjdk-11.0.2_linux-x64_bin.tar.gz && \
  rm -f openjdk-11.0.2_linux-x64_bin.tar.gz
